name: Deploy to Amazon ECS

on:
  release:
    types: [created]
    
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build and tag image
      run: |
          echo "Tag name is"
          echo ${{ github.ref }}

    - name: This is prod
      if:  ${{ !contains(github.ref_name, 'dev') }}
      run: |
          echo "This is a prod tag."

    - name: This is dev
      if: contains(github.ref_name, 'dev')
      run: |
          echo "This is a dev tag."
        
