name: Deploy to Amazon ECS

on:
  release:
    types: [created]
    
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build and tag image
      run: |
        echo ${{ github.ref }}
